name: Test
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Test and Sign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          gpg-private-key: ${{ secrets.SIGN_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Verify and Sign
        run: mvn --no-transfer-progress -B verify -P release
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

